/**
 * Dependency injection tokens.
 * Keep tokens centralized so services stay loosely coupled.
 */
export const TYPES = {
  Config: Symbol.for('Config'),
  Logger: Symbol.for('Logger'),
  RepositoryDefinitions: Symbol.for('RepositoryDefinitions'),
  RepositoryManager: Symbol.for('RepositoryManager'),
  KnowledgeStore: Symbol.for('KnowledgeStore'),
  SymbolExtractor: Symbol.for('SymbolExtractor'),
  Indexer: Symbol.for('Indexer'),
  FilesystemSearchEngine: Symbol.for('FilesystemSearchEngine'),
  SearchEngine: Symbol.for('SearchEngine'),
  SearchService: Symbol.for('SearchService'),
  DartAnalyzerClient: Symbol.for('DartAnalyzerClient'),
  UpdateRepositoriesHandler: Symbol.for('UpdateRepositoriesHandler'),
  RepositoryStatusHandler: Symbol.for('RepositoryStatusHandler'),
  SearchSourceHandler: Symbol.for('SearchSourceHandler'),
  FindWidgetHandler: Symbol.for('FindWidgetHandler'),
  ReindexHandler: Symbol.for('ReindexHandler'),
  ExplainWidgetHandler: Symbol.for('ExplainWidgetHandler'),
  SearchDocsHandler: Symbol.for('SearchDocsHandler'),
  FindExamplesHandler: Symbol.for('FindExamplesHandler'),
  FindTestsHandler: Symbol.for('FindTestsHandler'),
  TraceWidgetHandler: Symbol.for('TraceWidgetHandler'),
  FindBestPracticeHandler: Symbol.for('FindBestPracticeHandler'),
  ReviewProjectHandler: Symbol.for('ReviewProjectHandler'),
  FindIntendedBehaviorHandler: Symbol.for('FindIntendedBehaviorHandler'),
  ProjectScanner: Symbol.for('ProjectScanner'),
  AstAdapter: Symbol.for('AstAdapter'),
  OfficialReferenceResolver: Symbol.for('OfficialReferenceResolver'),
  CodeQualityAnalyzer: Symbol.for('CodeQualityAnalyzer'),
  StateManagementAnalyzer: Symbol.for('StateManagementAnalyzer'),
  ArchitectureAnalyzer: Symbol.for('ArchitectureAnalyzer'),
  MetricsEngine: Symbol.for('MetricsEngine'),
  ExplanationEngine: Symbol.for('ExplanationEngine'),
  RecommendationEngine: Symbol.for('RecommendationEngine'),
  ProjectHealthScorer: Symbol.for('ProjectHealthScorer'),
  RuleEngine: Symbol.for('RuleEngine'),
  ProjectReportBuilder: Symbol.for('ProjectReportBuilder'),
  AnalysisSessionStore: Symbol.for('AnalysisSessionStore'),
  EvidenceEngine: Symbol.for('EvidenceEngine'),
  KnowledgeEngine: Symbol.for('KnowledgeEngine'),
  ScoringEngine: Symbol.for('ScoringEngine'),
  TechnicalDebtEngine: Symbol.for('TechnicalDebtEngine'),
  FindingRelationshipEngine: Symbol.for('FindingRelationshipEngine'),
  ArchitectureMatchEngine: Symbol.for('ArchitectureMatchEngine'),
  IntendedBehaviourEngine: Symbol.for('IntendedBehaviourEngine'),
  PriorityActionEngine: Symbol.for('PriorityActionEngine'),
  AnalyzeCodeQualityHandler: Symbol.for('AnalyzeCodeQualityHandler'),
  AnalyzeStateManagementHandler: Symbol.for('AnalyzeStateManagementHandler'),
  AnalyzeArchitectureHandler: Symbol.for('AnalyzeArchitectureHandler'),
  ExplainFindingHandler: Symbol.for('ExplainFindingHandler'),
  ExploreFindingHandler: Symbol.for('ExploreFindingHandler'),
  ComplexityAnalyzer: Symbol.for('ComplexityAnalyzer'),
  TestingAnalyzer: Symbol.for('TestingAnalyzer'),
  DependencyAnalyzer: Symbol.for('DependencyAnalyzer'),
  PerformanceAnalyzer: Symbol.for('PerformanceAnalyzer'),
  DocumentationAnalyzer: Symbol.for('DocumentationAnalyzer'),
  AccessibilityAnalyzer: Symbol.for('AccessibilityAnalyzer'),
  AnalyzeComplexityHandler: Symbol.for('AnalyzeComplexityHandler'),
  AnalyzeDocumentationHandler: Symbol.for('AnalyzeDocumentationHandler'),
  AnalyzeTestingHandler: Symbol.for('AnalyzeTestingHandler'),
  AnalyzeDependenciesHandler: Symbol.for('AnalyzeDependenciesHandler'),
  AnalyzePerformanceHandler: Symbol.for('AnalyzePerformanceHandler'),
  AnalyzeAccessibilityHandler: Symbol.for('AnalyzeAccessibilityHandler'),
} as const;
